### PR TITLE
Basic auth code is only relevant on server

### PR DESCRIPTION
**Pull request by tonyxiao**

### CODE REVIEW

**Comment by cwaring** [comment]
Thanks, not sure how I missed that. :+1:

**Comment by tonyxiao** [comment]
How does the process of pushing this to atmosphere work? I'd like to get this change in my meteor app but not sure how to go about it.

**Comment by cwaring** [comment]
I've published a new release. Just run `meteor update` from your app to
install the new version.

Chris

**Comment by tonyxiao** [comment]
Got it, :+1:

**Pull request merged**
